[2023-12-26T13:20:16.621+0545] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-20T00:00:00+00:00 [queued]>
[2023-12-26T13:20:16.625+0545] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-20T00:00:00+00:00 [queued]>
[2023-12-26T13:20:16.626+0545] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-26T13:20:16.637+0545] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): fetch_and_store_metrics> on 2023-07-20 00:00:00+00:00
[2023-12-26T13:20:16.639+0545] {standard_task_runner.py:60} INFO - Started process 27381 to run task
[2023-12-26T13:20:16.641+0545] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'metrics_pipeline', 'fetch_and_store_metrics', 'scheduled__2023-07-20T00:00:00+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/taxi_metrics_dag.py', '--cfg-path', '/tmp/tmpoosd_6cz']
[2023-12-26T13:20:16.642+0545] {standard_task_runner.py:88} INFO - Job 204: Subtask fetch_and_store_metrics
[2023-12-26T13:20:16.666+0545] {task_command.py:423} INFO - Running <TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-20T00:00:00+00:00 [running]> on host Sarita-Thinkpad
[2023-12-26T13:20:16.730+0545] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='metrics_pipeline' AIRFLOW_CTX_TASK_ID='fetch_and_store_metrics' AIRFLOW_CTX_EXECUTION_DATE='2023-07-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-20T00:00:00+00:00'
[2023-12-26T13:20:16.746+0545] {python.py:201} INFO - Done. Returned value was: None
[2023-12-26T13:20:16.758+0545] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=metrics_pipeline, task_id=fetch_and_store_metrics, execution_date=20230720T000000, start_date=20231226T073516, end_date=20231226T073516
[2023-12-26T13:20:16.813+0545] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2023-12-26T13:20:16.844+0545] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-27T12:21:51.296+0545] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-20T00:00:00+00:00 [queued]>
[2023-12-27T12:21:51.301+0545] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-20T00:00:00+00:00 [queued]>
[2023-12-27T12:21:51.301+0545] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-27T12:21:51.313+0545] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): fetch_and_store_metrics> on 2023-07-20 00:00:00+00:00
[2023-12-27T12:21:51.315+0545] {standard_task_runner.py:60} INFO - Started process 13913 to run task
[2023-12-27T12:21:51.317+0545] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'metrics_pipeline', 'fetch_and_store_metrics', 'scheduled__2023-07-20T00:00:00+00:00', '--job-id', '410', '--raw', '--subdir', 'DAGS_FOLDER/taxi_metrics_dag.py', '--cfg-path', '/tmp/tmp00gv6602']
[2023-12-27T12:21:51.317+0545] {standard_task_runner.py:88} INFO - Job 410: Subtask fetch_and_store_metrics
[2023-12-27T12:21:51.341+0545] {task_command.py:423} INFO - Running <TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-20T00:00:00+00:00 [running]> on host Sarita-Thinkpad
[2023-12-27T12:21:51.387+0545] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='metrics_pipeline' AIRFLOW_CTX_TASK_ID='fetch_and_store_metrics' AIRFLOW_CTX_EXECUTION_DATE='2023-07-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-20T00:00:00+00:00'
[2023-12-27T12:21:57.414+0545] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "//home/sarita/Documents/apache-airflow-project/dags/taxi_metrics_dag.py", line 58, in fetch_and_store_metrics
    clickhouse_data = get_clickhouse_data()
  File "//home/sarita/Documents/apache-airflow-project/dags/taxi_metrics_dag.py", line 33, in get_clickhouse_data
    result = clickhouse_conn.query(query)
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/clickhouse_connect/driver/client.py", line 193, in query
    return self._query_with_context(query_context)
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 209, in _query_with_context
    response = self._raw_request(body,
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 433, in _raw_request
    self._error_handler(response)
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 357, in _error_handler
    raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: :HTTPDriver for https://github.demo.trial.altinity.cloud:8443 returned response code 400)
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 1290 (end of query) (line 23, col 11): ;

 FORMAT Native. . (SYNTAX_ERROR) (version 23.10.5.20 (official build))

[2023-12-27T12:21:57.429+0545] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=metrics_pipeline, task_id=fetch_and_store_metrics, execution_date=20230720T000000, start_date=20231227T063651, end_date=20231227T063657
[2023-12-27T12:21:57.453+0545] {standard_task_runner.py:107} ERROR - Failed to execute job 410 for task fetch_and_store_metrics (:HTTPDriver for https://github.demo.trial.altinity.cloud:8443 returned response code 400)
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 1290 (end of query) (line 23, col 11): ;

 FORMAT Native. . (SYNTAX_ERROR) (version 23.10.5.20 (official build))
; 13913)
[2023-12-27T12:21:57.495+0545] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-27T12:21:57.505+0545] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-27T12:23:17.256+0545] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-20T00:00:00+00:00 [queued]>
[2023-12-27T12:23:17.261+0545] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-20T00:00:00+00:00 [queued]>
[2023-12-27T12:23:17.261+0545] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-27T12:23:17.273+0545] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): fetch_and_store_metrics> on 2023-07-20 00:00:00+00:00
[2023-12-27T12:23:17.275+0545] {standard_task_runner.py:60} INFO - Started process 13951 to run task
[2023-12-27T12:23:17.277+0545] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'metrics_pipeline', 'fetch_and_store_metrics', 'scheduled__2023-07-20T00:00:00+00:00', '--job-id', '415', '--raw', '--subdir', 'DAGS_FOLDER/taxi_metrics_dag.py', '--cfg-path', '/tmp/tmpnpqow4za']
[2023-12-27T12:23:17.277+0545] {standard_task_runner.py:88} INFO - Job 415: Subtask fetch_and_store_metrics
[2023-12-27T12:23:17.302+0545] {task_command.py:423} INFO - Running <TaskInstance: metrics_pipeline.fetch_and_store_metrics scheduled__2023-07-20T00:00:00+00:00 [running]> on host Sarita-Thinkpad
[2023-12-27T12:23:17.347+0545] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='metrics_pipeline' AIRFLOW_CTX_TASK_ID='fetch_and_store_metrics' AIRFLOW_CTX_EXECUTION_DATE='2023-07-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-20T00:00:00+00:00'
[2023-12-27T12:23:25.543+0545] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "//home/sarita/Documents/apache-airflow-project/dags/taxi_metrics_dag.py", line 58, in fetch_and_store_metrics
    clickhouse_data = get_clickhouse_data()
  File "//home/sarita/Documents/apache-airflow-project/dags/taxi_metrics_dag.py", line 33, in get_clickhouse_data
    result = clickhouse_conn.query(query)
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/clickhouse_connect/driver/client.py", line 193, in query
    return self._query_with_context(query_context)
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 209, in _query_with_context
    response = self._raw_request(body,
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 433, in _raw_request
    self._error_handler(response)
  File "/home/sarita/Documents/apache-airflow-project/.venv/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 357, in _error_handler
    raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: :HTTPDriver for https://github.demo.trial.altinity.cloud:8443 returned response code 400)
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 1290 (end of query) (line 23, col 11): ;

 FORMAT Native. . (SYNTAX_ERROR) (version 23.10.5.20 (official build))

[2023-12-27T12:23:25.558+0545] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=metrics_pipeline, task_id=fetch_and_store_metrics, execution_date=20230720T000000, start_date=20231227T063817, end_date=20231227T063825
[2023-12-27T12:23:25.599+0545] {standard_task_runner.py:107} ERROR - Failed to execute job 415 for task fetch_and_store_metrics (:HTTPDriver for https://github.demo.trial.altinity.cloud:8443 returned response code 400)
 Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 1290 (end of query) (line 23, col 11): ;

 FORMAT Native. . (SYNTAX_ERROR) (version 23.10.5.20 (official build))
; 13951)
[2023-12-27T12:23:25.611+0545] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-27T12:23:25.627+0545] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
